[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer-runs = 8000
evm_version = "shanghai" # "paris" fo Avalanche, "shanghai" for other chains

[fmt]
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"

[rpc_endpoints]
sepolia = "${RPC_ETH_SEPOLIA}"
mainnet = "${RPC_ETH_MAINNET}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
